# syntax=docker/dockerfile:1
ARG RUBY_VERSION=4.0.1
FROM docker.io/library/ruby:$RUBY_VERSION-slim-trixie

# Set absolute path as requested
WORKDIR /home/asmadeous/Work/proxysock-api

# Install 2026 system dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential git curl libpq-dev libyaml-dev pkg-config libvips libjemalloc2 postgresql-client \
    ansible sshpass openssh-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV RAILS_ENV=development \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_APP_CONFIG="/usr/local/bundle" \
    LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libjemalloc.so.2"

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
