services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Automatically prepares all 4 databases (primary, cache, queue, cable)
    command: >
      bash -c "bin/rails db:prepare && 
               rm -f tmp/pids/server.pid && 
               bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/home/asmadeous/Work/proxysock-api:cached
      - rails_bundle_2026:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USERNAME=asmadeous
      - DB_PASSWORD=Asmadeous@2025
      - RAILS_ENV=development
    profiles: [ "dev" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - default


volumes:
  rails_bundle_2026:
