---
- name: Change Windows Administrator Password
  hosts: all
  vars:
    new_password: "{{ password }}"
    target_user: "{{ user | default('Administrator') }}"

  pre_tasks:
    - name: Ensure password is defined
      fail:
        msg: "password must be defined for security reasons."
      when: password is not defined

  tasks:
    - name: Change user password
      win_user:
        name: "{{ target_user }}"
        password: "{{ password }}"
        state: present
        no_log: true
